module Next
  class Config < ConfigX::Config
    interface _NextDebugConfig
      def receive: -> bool
      def autoreceive: -> bool
      def unhandled: -> bool
      def lifecycle: -> bool
    end

    interface _ActorConfig
      def creation_timeout: -> Integer
    end

    interface _NextConfig
      def logger: -> String?
      def stdout_log_level: -> String
      def debug: -> _NextDebugConfig
      def actor: -> _ActorConfig
      def log_config_on_start: -> bool
    end

    def next: -> _NextConfig
  end
end
