module Next
  module Context
    include Concurrent::Synchronization::_LockableObject

    attr_reader children: Hash[String, Reference]
    attr_accessor identity: Reference

    attr_accessor parent: Reference

    def actor_of: [T < Actor] (Props[T], ?String)-> Reference

    def sender: -> Reference
    def executor: -> Concurrent::AbstractExecutorService
  end
end
