module Next
  class Core[ActorClass < Actor] < ::Concurrent::Synchronization::LockableObject
    include Context
    include FaultTolerance

    @actor: ActorClass?

    attr_reader serialized_execution: SerializedExecution
    attr_reader props: Props[ActorClass]

    def initialize: ({props: Props[ActorClass], identity: Reference, parent: Reference?}) -> void

    def process_envelope: (Envelope)-> void

    def run: -> void

    def schedule_execution: (Envelope) { (Envelope) -> void } -> void

    private

    def actor: -> ActorClass

    def actor=: (ActorClass) -> ActorClass

    def actor_initialized?: -> bool

    def auto_receive_message: (untyped)-> void

    def current_behaviour: -> Symbol

    def handle_death_watch_notification: (Reference) -> void

    def initialize_actor: (Reference)-> void

    def process_message: (untyped) -> void

    def process_system_message: (untyped) -> void

    def supervise: (Reference) -> void
  end
end
