module Next
  class Envelope < Data
    attr_reader message: untyped
    attr_reader sender: Reference

    def self.new: (message: untyped, sender: Reference) -> instance
                | (untyped, Reference) -> instance

    def system_message?: -> bool
  end
end
