module Next
  class EventBus < Actor
    def self.props: -> Props[EventBus]

    attr_reader subscriptions: Hash[untyped, Set[Reference]]

    def initialize: -> void

    def receive: (untyped) -> void

    private

    def subscribe: (event: untyped, subscriber: Reference) -> void

    def publish: (event: untyped) -> void

    def subscribers: (untyped) -> Set[Reference]

    def unsubscribe: (subscriber: Reference) -> void
  end
end
