module Next
  class EventStream
    attr_reader event_bus: Reference

    def initialize: (event_bus: Reference) -> void

    def publish: (untyped) -> self

    def subscribe: (Reference, untyped) -> self

    def unsubscribe: (Reference) -> self
  end
end
