module Next
  module Testing
    module Expectations
      attr_reader jailbreak: Concurrent::Channel

      def await_condition: (?timeout: Numeric, ?interval: Numeric, ?message: String) { -> bool } -> void

      def expect_all_messages: (*untyped, ?timeout: Numeric) -> void

      def expect_log: (untyped, level: Symbol?, ?timeout: Numeric)-> untyped

      def expect_message: (untyped, ?timeout: Numeric) { -> void } -> untyped

      def expect_no_log: (untyped, ?timeout: Numeric) { -> void } -> untyped

      def expect_no_message: (untyped, ?timeout: Numeric, ?interval: Numeric)-> untyped

      def fish_for_message: (untyped, ?timeout: Numeric) { -> void } -> untyped

      private

      def expect_match: (untyped, Envelope, String?)-> void

      def expect_not_match: (untyped, Envelope, String?)-> void

      def receive_many: (Integer, ?max: Numeric) -> Array[untyped]

      def receive_one: (timeout: Numeric) -> Fear::Option[untyped]
    end
  end
end
