module Next
  class Logger < Actor
    def self.props: [T < Logger ](logger: T) -> Props[Logger]

    attr_reader logger: ::Logger

    def initialize: (logger: ::Logger) -> void

    def post_stop: -> void

    def pre_start: -> void

    def receive: (LogEvent) -> void
  end
end
