module Next
  class Reference
    def initialize: [T < Actor] (Props[T], ?name: String, parent: Reference?, system: System) -> self

    attr_reader core: Core[Actor]
    attr_reader name: String
    attr_reader props: Props[Actor]

    alias << tell

    def ask: (untyped, ?Reference)-> Fear::Future[untyped]

    def ask!: (untyped, ?Reference, ?timeout: Numeric) -> Fear::Option[untyped]

    def tell: (untyped, ?Reference) -> self

    def path: -> String

    private

    def start_actor: (parent: Reference?, system: System)-> Core[Actor]
  end
end
