module Next
  class Reference
    attr_reader parent: Reference?

    def initialize: [T < Actor] (Props[T], ?name: String, parent: Reference?, system: System) -> self

    attr_reader core: Core[Actor]
    attr_reader name: String

    alias << tell

    def stop: -> Fear::Future[Terminated]

    def ask: (untyped, ?Reference)-> Fear::Future[untyped]

    def ask!: (untyped, ?Reference, ?timeout: Numeric) -> Fear::Option[untyped]

    def tell: (untyped, ?Reference) -> self

    def path: -> String

    def terminated?: -> bool

    def termination_future: -> Fear::Future[Terminated]

    private

    def accepting_messages: (message: untyped, sender: Reference) { (untyped, Reference) -> void } -> void

    def start_actor: [T < Actor] (parent: Reference?, system: System, props: Props[T])-> Core[T]
  end
end
