module Next
  module SystemMessages
    class Failed < Data
      include SystemMessage

      attr_reader cause: StandardError
      attr_reader child: Reference

      def self.new: (child: Reference, cause: StandardError) -> instance
                  | (Reference, StandardError) -> instance
    end
  end
end
