module Next
  module SystemMessages
    class Initialize < Data
      include SystemMessage

      attr_reader parent: Reference?

      def self.new: (parent: Reference?) -> instance
                  | (Reference?) -> instance
    end
  end
end
