module Next
  module SystemMessages
    class Recreate < Data
      include SystemMessage

      attr_reader cause: StandardError

      def self.new: (cause: StandardError) -> instance
                  | (StandardError) -> instance
    end
  end
end
