module Next
  module SystemMessages
    class Resume
      attr_reader caused_by_failure: StandardError

      def initialize: (StandardError) -> void

      def deconstruct: -> [StandardError]

      def deconstruct_key: -> { caused_by_failure: StandardError }
    end
  end
end
