module Next
  module SystemMessages
    class Resume < Data
      attr_reader caused_by_failure: StandardError

      def self.new: (caused_by_failure: StandardError) -> instance
                  | (StandardError) -> instance
    end
  end
end
