module Next
  module SystemMessages
    class Supervise < Data
      include SystemMessage

      attr_reader child: Reference

      def self.new: (child: Reference) -> instance
                  | (Reference) -> instance
    end
  end
end
