module Next
  module Logging
    # This is the main interface for logging.
    #
    class Log
      def info: (untyped, ?String?) -> void

      def debug: (untyped, ?String?) -> void

      def warn: (untyped, ?String?) -> void

      def error: (untyped, ?String?) -> void

      def fatal: (untyped, ?String?) -> void
    end
  end
end
