module Next
  PoisonPill: AutoReceivedMessage

  VERSION: String

  def self?.props: [T < Actor] (untyped, **untyped) -> Props[T]
  def self?.default_executor: -> Concurrent::AbstractExecutorService
  def self?.system: (String) { () [self: Dry::Configurable::_Settings] -> void }-> System
end
