module Concurrent
  module Synchronization
    interface _LockableObject
      def synchronize: [T] () { () -> T }-> T
    end

    class LockableObject
      include _LockableObject
    end
  end
end
