module Next
  class SerializedExecution
    class Job < Data
      attr_reader executor: Concurrent::AbstractExecutorService
      attr_reader envelope: Envelope
      attr_reader block: Proc

      def self.new: (executor: Concurrent::AbstractExecutorService, envelope: Envelope, block: Proc) -> instance
                  | (Concurrent::AbstractExecutorService, Envelope, Proc) -> instance

      def call: -> void
    end
  end
end
