module Next
  class Logger < Actor
    class Unknown < LogEvent
      def self.new: (message: untyped, ?progname: String?) -> instance
      def initialize: (message: untyped, ?progname: String?) -> void
    end
  end
end
